name: CI/CD Pipeline

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Docker login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build & Push Docker Image
        run: |
          IMAGE_TAG=${GITHUB_REF##*/}
          docker build -t kusuma3012/product-catalog:$IMAGE_TAG .
          docker push kusuma3012/product-catalog:$IMAGE_TAG

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/namespace-v1.yaml
          kubectl apply -f k8s/deployment-v1.yaml
          kubectl apply -f k8s/service-v1.yaml
          kubectl apply -f k8s/ingress.yaml
